Ttr obs
SFU-MARS/optimized_dp pull request #37
Opened 2024-11-01 20:34 UTC by Hu-Hanyang

2025-03-20 21:20 UTC, mochen72 commented
This should be ready to be merged. Main changes

TTR computations:
- Can now allow constraints to be specified in TTR computations
- Added functions for computing trajectories from value functions

Grid
- Add __str__ method
- Add batch evaluation of states on value functions

Miscellaneous
- Better code formatting
- Minor changes to several classes representing system dynamics

2025-04-30 23:41 UTC, buinm commented on odp/Plots/plot_options.py
downsample member variable is missing in the init's variable list

2025-07-07 18:19 UTC, buinm requested changes
Thank you for the changes. It mostly looks good. However, before merging, could you please make changes to address the following:
* paper_examples/ folder does not exist in master branch, might be it is only applicable to your branch. You should remove it
* Please address my comment on using `np.logical_and` instead of operator `&` (its behavior is not well-defined) when extracting TTR
* In `solver.py`, can we use `computeTimeToReach` to conditionally check before creating new numpy array for TTR? If `computeTimeToReach` is false, we don't have to initialize memory array, which saves us memory especially in high-dimensional case.

2025-07-07 22:09 UTC, buinm approved these changes

2025-07-07 22:13 UTC, merged